{{- range $index, $service := .Values.services }}
{{- if eq $service.type "deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          command: ["uvicorn"]
          args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
          resources: 
            {{- if .resources }}
            requests:
              cpu: "{{ .resources.requests.cpu }}"
              memory: "{{ .resources.requests.memory }}"
            limits:
              cpu: "{{ .resources.limits.cpu }}"
              memory: "{{ .resources.limits.memory }}"
            {{- else }}
            {}
            {{- end }}
          ports:
            - containerPort: {{ .targetPort }}
          env:
            {{- if .env }}
            {{- range .env }}
              {{- if .value }}
            - name: {{ .name }}
              value: "{{ .value }}"
              {{- else if .key }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
              {{- end }}
            {{- end }}
            {{- end }}
          {{- if .extraArgs }}
          args:
            {{- range .extraArgs }}
            - {{ . }}
            {{- end }}
          {{- end }}
{{- end }}
{{- end }}
