apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - secretName: fastapi-secret
      hosts:
        - fastapi.cours2-datascientest2024.cloudns.ch 
  rules:
    - host: fastapi.cours2-datascientest2024.cloudns.ch
      http:
        paths:
          - path: /api/v1/movies
            pathType: Prefix
            backend:
              service:
                name: movie-service
                port:
                  number: 80
          - path: /api/v1/casts
            pathType: Prefix
            backend:
              service:
                name: cast-service
                port:
                  number: 80
