apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
type: Opaque
data:
  POSTGRES_USER: ZGF0YXNjaWVudGVzdG1vdmll
  POSTGRES_PASSWORD: ZGF0YXNjaWVudGVzdG1vdmllMjAyNQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
type: Opaque
data:
  POSTGRES_USER: ZGF0YXNjaWVudGVzdGNhc3Q=
  POSTGRES_PASSWORD: ZGF0YXNjaWVudGVzdGNhc3QyMDI1
