{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .port }}  # Port externe du service
      targetPort: {{ .targetPort }}  # Port interne du pod
      {{- if .nodePort }}
      nodePort: {{ .nodePort }} 
      {{- end }}
  {{- if .serviceType }}
  type: {{ .serviceType }}  
  {{- else }}
  type: ClusterIP 
  {{- end }}
{{- end }}
