{{- range $index, $service := .Values.services }}
{{- if eq $service.type "statefulset" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $service.name }}
spec:
  serviceName: {{ $service.name }}-service
  replicas: {{  $service.replicas }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          ports:
            - containerPort: {{ $service.port }}
          env:
             {{- if .env }}
            {{- range .env }}
              {{- if .value }}
            - name: {{ .name }}
              value: "{{ .value }}"
              {{- else if .key }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
              {{- end }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: {{ $service.name }}-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: {{ $service.name }}-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $service.volumeClaimTemplate.resources.requests.storage }}
        storageClassName: {{ $service.volumeClaimTemplate.storageClassName }}
{{- end }}
{{- end }}
        