services:
  
  - name: movie
    type: "deployment"
    image:
      repository: mirael13/movie_service
      tag: latest
    port: 80
    targetPort: 8000
    serviceType: ClusterIP
    env:
      - name: DATABASE_USER
        key: POSTGRES_USER
        secretName: "movie-db-secret"
      - name: DATABASE_PASSWORD
        key: POSTGRES_PASSWORD
        secretName: "movie-db-secret"
      - name: DATABASE_NAME
        value: "moviedb"
      - name: DATABASE_HOST
        value: "movie-db-service"
      - name: DATABASE_PORT
        value: "5432"
      - name: DATABASE_URL
        value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
      - name: DATABASE_URI
        value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
      - name: CAST_SERVICE_HOST_URL
        value: "http://cast-service/api/v1/casts/"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    hpa: 
      minReplicas: 1
      maxReplicas: 2
      cpuTarget: 70
      
  - name: cast
    type: "deployment"
    image:
      repository: mirael13/cast_service
      tag: latest
    port: 80
    targetPort: 8000
    serviceType: ClusterIP
    env:
      - name: DATABASE_USER
        key: POSTGRES_USER
        secretName: "cast-db-secret"
      - name: DATABASE_PASSWORD
        key: POSTGRES_PASSWORD
        secretName: "cast-db-secret"
      - name: DATABASE_NAME
        value: "castdb"
      - name: DATABASE_HOST
        value: "cast-db-service"
      - name: DATABASE_PORT
        value: "5432"
      - name: DATABASE_URL
        value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
      - name: DATABASE_URI
        value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    hpa: 
      minReplicas: 1
      maxReplicas: 2
      cpuTarget: 70
      
  
  
  - name: movie-db
    type: "statefulset"
    replicas: 1
    image:
      repository: postgres
      tag: latest
    port: 5432
    targetPort: 5432
    serviceType: ClusterIP
    env:
      - name: POSTGRES_USER
        key: POSTGRES_USER
        secretName: "movie-db-secret"
      - name: POSTGRES_PASSWORD
        key: POSTGRES_PASSWORD
        secretName: "movie-db-secret"
      - name: POSTGRES_DB
        value: "moviedb"
    volumeClaimTemplate:
      resources:
        requests:
          storage: 10Gi
      storageClassName: "local-path"
    
  - name: cast-db
    type: "statefulset"
    replicas: 1
    image:
      repository: postgres
      tag: latest
    port: 5432
    targetPort: 5432
    serviceType: ClusterIP
    env:
      - name: POSTGRES_USER
        key: POSTGRES_USER
        secretName: "cast-db-secret"
      - name: POSTGRES_PASSWORD
        key: POSTGRES_PASSWORD
        secretName: "cast-db-secret"
      - name: POSTGRES_DB
        value: "castdb"
    volumeClaimTemplate:
      resources:
        requests:
          storage: 10Gi
      storageClassName: "local-path"
    